# Generated by Django 5.0.3 on 2025-06-16 06:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesshours',
            options={'ordering': ['day']},
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='opening_time',
        ),
        migrations.AddField(
            model_name='businesshours',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 16, 6, 18, 26, 105585, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesshours',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='BusinessTimePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('period_name', models.CharField(blank=True, help_text="Optional name like 'Morning', 'Afternoon', 'Evening'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_periods_set', to='businesses.businesshours')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
