# Generated by Django 5.2.1 on 2025-08-07 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_businesscategory_business_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscategory',
            name='is_default',
            field=models.BooleanField(default=False, help_text="Default categories that can't be deleted"),
        ),
        migrations.CreateModel(
            name='CategoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(help_text='Name of the business requesting this category', max_length=200)),
                ('requested_category_name', models.CharField(max_length=100)),
                ('requested_description', models.TextField()),
                ('service_examples', models.TextField(help_text='Examples of services this business provides')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('merged', 'Merged with Existing Category')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_category', models.ForeignKey(blank=True, help_text='Category created from this request', null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.businesscategory')),
                ('merged_with_category', models.ForeignKey(blank=True, help_text='Existing category this request was merged with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_requests', to='businesses.businesscategory')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_category_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category Request',
                'verbose_name_plural': 'Category Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='business',
            name='category_request',
            field=models.ForeignKey(blank=True, help_text='Category request made by this business (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.categoryrequest'),
        ),
    ]
