# Generated by Django 5.2.1 on 2025-09-09 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_businesscategory_is_default_categoryrequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='category_request',
        ),
        migrations.DeleteModel(
            name='CategoryRequest',
        ),
    ]
